### PR TITLE
Add convey payload to connect event

### PR DESCRIPTION
**Pull request by Symbianx**
This change adds the convey payload to the Connect event as discussed in #271. 
When used together with Comcast/talaria#43 will allow us to take more informed actions based on the device state.

### CODE REVIEW

**Comment by schmidtw** [comment]
@johnabass Can we merge this or are there changes needed?

**Comment by johnabass** [comment]
We had some internal discussions and had decided to delay this due to performance concerns.  Has anything changed?

**Comment by Symbianx** [comment]
@johnabass @schmidtw 
Although we understand your concern about performance, we think this change would really benefit all companies using this software, being able to leverage the information contained in the convey payload, such as reboot reasons and uptime, is what makes the Connect event really valuable for extracting business indicators and providing a better costumer experience.

Can we try to workout a solution regarding the performance impact and still maintain the benefits of the pull request?
Is your concern based on the Marshalling of the object? We could move the marshalling to the line before the logging, since the logger is also marshalling to JSON, passing the already marshalled string in the log should leave us with about the same performance. What do you think?

**Comment by schmidtw** [comment]
Yeah, this is a good step forward.  The biggest concern we have is actually with the other part of the PR where the internal talaria events get propagated out.  Given the volume of some of them (and the value of some & not others) we will need to add some knobs to the other PR.

**Pull request merged**
